### ISSUE TITLE
get_member_name() never fails. 

### ISSUE THREAD

**Issue by seivan** [grovesNL/spirv_cross#110]
`ast.get_member_name()` never fails, it just returns an empty string. 
If this is by design because it's not considered an error, then maybe the `Result<T>` should be changed to `Result<Option<T>>`?

**Comment by cheako** [comment]
See https://internals.rust-lang.org/t/pre-rfc-none-if-string-is-empty/6742

**Comment by seivan** [comment]
That makes sense if you were working with Strings directly. From my PoV if a member is missing, it's not a string to begin with, it's nothing.

**Comment by grovesNL** [comment]
It's pretty unlikely to fail but could happen while creating Rust `String` by reading from `*c_char`. We'll probably keep it as `Result` for now.
