### ISSUE TITLE
Speed up compiling by skipping targets 

### ISSUE THREAD

**Issue by seivan** [grovesNL/spirv_cross#114]
Could things be sped up if https://github.com/grovesNL/spirv_cross/blob/master/bindings_generator/src/main.rs#L52 was behind a conditional to avoid wasm?

**Comment by grovesNL** [comment]
`bindings_generator` is run manually, not automatically. So I don't think this will help regular build times for crates downstream.

**Comment by seivan** [comment]
That makes sense, thanks.
