### ISSUE TITLE
Minimize the vendored code

### ISSUE THREAD

**Issue by kvark** [grovesNL/spirv_cross#120]
I'm trying to [vendor](https://phabricator.services.mozilla.com/differential/diff/177695/changesets/?after=1707835) `spirv_cross`, and there appear to be a lot of seemingly unneeded files in the repo, e.g. everything in `reference` folder.

We need to make it a smaller dependency in terms of code... Another alternative we are considering is only shipping the Vulkan backend until the Javelin project is mature enough, but that's very risky.

**Comment by kvark** [comment]
Here is an idea: fork SPIRV-Cross, remove the test suite permanently and depend on it.

**Comment by kvark** [comment]
Trying this in `wgpu-test` fork now: https://github.com/kvark/spirv_cross/commit/2940c164b6d62c5e2fb3a29ae60ad629ce990107

**Comment by grovesNL** [comment]
This should be fixed by #123
