### ISSUE TITLE
Texture data, arrayed/depth?

### ISSUE THREAD

**Issue by cheako** [grovesNL/spirv_cross#133]
https://github.com/KhronosGroup/SPIRV-Cross/issues/1281

I see https://github.com/grovesNL/spirv_cross/blob/master/spirv_cross/src/wrapper.cpp#L370 and it look kindof empty.  Shouldn't there be a lot more going on?  I only want arrayed for now.

Edit: I actually can assume this for my project.

**Comment by grovesNL** [comment]
Could you clarify which parts are missing? We can update the wrapper to expose anything else we need

**Comment by cheako** [comment]
That's what I'm asking!

I looked closer at the SPIRv docs and it looks like most of the ImageType struct is just bool. For my use case the arrayed member is the important part.

**Comment by grovesNL** [comment]
Do we need to expose something else?

**Comment by cheako** [comment]
Good question.

**Comment by grovesNL** [comment]
It sounds like this is working ok so I'll close this for now. Please let me know if it's not working for you and we could reopen this.
