### ISSUE TITLE
stage_inputs format

### ISSUE THREAD

**Issue by erlendp** [grovesNL/spirv_cross#139]
Just wondering how to get the stride of a vertex input so I can create my buffer descriptor correctly. Calling `get_type(input.type_id)` on `layout(location = 0) in vec4 a_Pos;` appears to return a `Float { array: [] }`. There doesn't seem to be any way to get the actual `vecsize` which I was expecting. Am I missing something here?

**Comment by grovesNL** [comment]
Hi @erlendp! Were you able to figure this out?

**Comment by erlendp** [comment]
@grovesNL I've put this down for a while, while I work on other projects, but I'm still keen to find a solution!

**Comment by sir-earl** [comment]
Looks like the required fields hadn't been mapped through yet, so I've added a PR to expose them:

https://github.com/grovesNL/spirv_cross/pull/142

**Comment by grovesNL** [comment]
Looks like this was fixed by #142, thanks @sir-earl!
