### ISSUE TITLE
Make compiler options non-exhaustive

### ISSUE THREAD

**Issue by kvark** [grovesNL/spirv_cross#153]
Looking at https://github.com/gfx-rs/gfx/pull/3356, it seems to me that we could avoid breaking spirv-cross changes if we make the structure non-exhaustive.

**Comment by grovesNL** [comment]
Yeah this would probably work alright, I guess we wouldn't be able to use struct initializers anymore though.

e.g. This would be ok:
```rust
let mut options = CompilerOptions::default();
options.force_zero_initialized_variables = true;
```
But we wouldn't be able to do:
```rust
let options = CompilerOptions {
  force_zero_initialized_variables: true,
  ..Default::default()
};
```

**Comment by kvark** [comment]
Yeah, it's fine, since this is all internal to backends.
