### ISSUE TITLE
Conditionally compile

### ISSUE THREAD

**Issue by Michael-Lfx** [grovesNL/spirv_cross#90]
Is it better to conditionally compile these files for reducing binary size for mobile app?
https://github.com/grovesNL/spirv_cross/blob/6bcf6a58e776bb1bc4d49d8e232c7d48f4793f15/spirv_cross/build.rs#L26-L28

**Comment by grovesNL** [comment]
Sure, sounds reasonable to me. Maybe we could have features like `glsl`, `hlsl`, and `msl`, so we could conditionally compile both the C++ source file and the Rust module for each feature.

**Comment by Michael-Lfx** [comment]
Yeah. Thanks for reply so quickly. I am looking forward to the next release.

**Comment by grovesNL** [comment]
This is fixed in the latest release (0.13.0): features `glsl`, `hlsl`, and `msl` are now available.
